# Generated by Django 2.0.3 on 2018-05-10 04:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='item',
            name='completed_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='item',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
    ]
