# Generated by Django 2.0.3 on 2018-05-24 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_auto_20180522_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='attributed_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
