# Generated by Django 2.0.3 on 2018-05-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_auto_20180510_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_important',
            field=models.BooleanField(default=True),
        ),
    ]
