# Generated by Django 2.0.3 on 2018-05-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0003_item_is_important'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterField(
            model_name='item',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
