# Generated by Django 2.0.3 on 2018-05-11 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roadmap', '0006_subtheme_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('entity_uid', models.PositiveIntegerField()),
                ('entity_type', models.CharField(choices=[('Sous-thème', 'Sous-thème'), ('Item', 'Item'), ('Commentaire', 'Commentaire')], max_length=100)),
                ('old_value', models.TextField()),
                ('action', models.CharField(choices=[('Création', 'Création'), ('Edition', 'Edition'), ("Changement d'ordre", "Changement d'ordre")], max_length=200)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
