# Generated by Django 2.0.3 on 2018-05-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0007_eventlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='entity_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='old_value',
            field=models.TextField(null=True),
        ),
    ]
