# Generated by Django 2.0.3 on 2018-05-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0008_auto_20180511_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventlog',
            old_name='old_value',
            new_name='value',
        ),
    ]
